[package]
name = "crc"
version = "1.5.0"
authors = ["mrhooray <ruihu.pvt@gmail.com>"]
description = "Rust implementation of CRC(32, 64) with support of various standards"
keywords = ["crc", "crc32", "crc64", "hash", "checksum"]
readme = "README.md"
repository = "https://github.com/mrhooray/crc-rs.git"
license = "MIT"

[dependencies]
crc-core = "0.1"
build_const = { version = "0.2", default-features = false }

[build-dependencies]
crc-core = "0.1"
build_const = "0.2"

[features]
std = []
default = ["std"]
